GET http://localhost:5033/api/stats/users/count

###
GET http://localhost:5033/api/reviews/top?limit=3


###
GET http://localhost:5033/api/profile/favorites
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMiIsImVtYWlsIjoiYW1tYXJtb2hhbWVkNTEwNUBnbWFpbC5jb20iLCJqdGkiOiIwNzU4M2JiNy0wNWIyLTQwODUtYTg4Yi1iODgyNWVlNjU4OGUiLCJuYW1lIjoiQW1tYXIgTW9oYW1lZCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlJlYWRlciIsImV4cCI6MTc4MzI2NDI4MywiaXNzIjoiQmF5bkFsU3V0b29yQVBJIiwiYXVkIjoiQmF5bkFsU3V0b29yQ2xpZW50cyJ9.ss52bbod54Ft2fzbInohEyUQahD6BayKhnbTJknCnZE


###
GET http://localhost:5033/api/dashboard/users/count
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJhZG1pbkBiYXluYWxzdXRvb3IuY29tIiwianRpIjoiNDc1YjUzNGEtNDlmYi00NjQ1LWEwNjEtZWY5OTE0ZWZiYWNkIiwibmFtZSI6IlN5c3RlbSBBZG1pbmlzdHJhdG9yIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJwZXJtaXNzaW9uIjpbIk1hbmFnZUJvb2tzIiwiTWFuYWdlQXV0aG9ycyIsIk1hbmFnZVVzZXJzIiwiVmlld0xvZ3MiXSwiZXhwIjoxNzgzNDYyNTM1LCJpc3MiOiJCYXluQWxTdXRvb3JBUEkiLCJhdWQiOiJCYXluQWxTdXRvb3JDbGllbnRzIn0.TrcSJGjI1ezgCEKzbUMu1-Ur6JZ_zER2MdqlUQRxdv0